name: agentictrader
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - fastapi=0.103.0
  - uvicorn=0.23.2
  - pytesseract=0.3.10
  - notion-client=2.2.1
  - requests=2.31.0
  - python-dotenv=1.0.1
  - numpy=1.26.4
  - google-cloud-vision=3.7.2
  - groq=0.18.0
  - pandas=2.1.4
  - pydantic=2.5.0
  - aiohttp>=3.11.16
  - openai>=1.73.0
  - optuna>=4.3.0
  - sqlalchemy>=2.0.40
  - pip
  - pip:
      - opencv-python>=4.9.0
      - metatrader5>=5.0.45
      - dspy-ai>=2.4.5
      - yfinance>=0.2.44